M48
; DRILL file {KiCad 6.0.0-d3dd2cf0fa~116~ubuntu20.04.1} date Sun 09 Jan 2022 10:45:02 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-01-09T22:45:02+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.0-d3dd2cf0fa~116~ubuntu20.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
%
G90
G05
T1
X102.0Y-102.0
X102.0Y-148.0
X198.0Y-52.0
X198.0Y-106.0
T0
M30
